### ISSUE TITLE
Application closes if the description is null

### ISSUE THREAD

**Issue by NightSkyAsHate** [BbeHumble/TaskManagerApplication#2]
### Steps to repeat the bug:
1.  Create task with `any` text
2. Click `Сохранить` button
3. Click on your new task
4. Click on description textView and enter any value but `don't click anywhere else and don't close the keyboard`
5. Click `back` button

### Result
     The application crashes
----
### Expected result
     The application saves the text and return to main screen

### What to do
     Add a listener and save text every time the user enteres the text

**Comment by BbeHumble** [comment]
Fixed. It was because of deleting subtasks with string = "". But subtaskList was null
